name: Holiday Hub CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 21.9.0
        uses: actions/setup-node@v3
        with:
          node-version: "21.9.0"
      - run: npm install
      - run: rum run watch --prefix client
      - run: npm test
